=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by NTT (norg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns="Apertum" targetNamespace="Apertum" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Order">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="POHead">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="OrderDetails">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="SupplierOrderReference" type="xs:string"/>
										<xs:element name="BuyerOrderReference" type="xs:string"/>
										<xs:element name="TextHeader" type="xs:string"/>
										<xs:element name="TextFooter" type="xs:string"/>
										<xs:element name="SupplierOrderDate" type="xs:date"/>
										<xs:element name="BuyerOrderDate" type="xs:date"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Currency">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="CurrencyCode" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="TermsOfPayment">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Description" type="xs:string"/>
										<xs:element name="NetDays" type="xs:int"/>
										<xs:element name="Discount1" type="ns:Discount"/>
										<xs:element name="Discount2" type="ns:Discount"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="TermsOfDelivery">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DelivType" type="xs:string"/>
										<xs:element name="TransportType" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Buyer" type="ns:Partner"/>
				<xs:element name="Supplier" type="ns:Partner"/>
				<xs:element name="DeliverTo" type="ns:Partner"/>
				<xs:element name="InvoiceTo" type="ns:Partner"/>
				<xs:element name="POLine">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LineNo" type="xs:string"/>
							<xs:element name="Product" type="ns:Product"/>
							<xs:element name="Price" type="ns:Price"/>
							<xs:element name="Quantity" type="ns:Quantity"/>
							<xs:element name="RequestedDeliveryDate">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DateYear" type="xs:int"/>
										<xs:element name="DateWeek" type="xs:int"/>
										<xs:element name="Date" type="xs:date"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Discount" type="ns:Discount"/>
							<xs:element name="Amount" type="ns:Amount"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="OrderTotal">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="NumberOfLines" type="xs:positiveInteger"/>
							<xs:element name="TotalAmount">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="ns:Amount">
											<xs:sequence>
												<xs:element name="VAT_AmountTotal" type="xs:int"/>
											</xs:sequence>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Address">
		<xs:sequence>
			<xs:element name="Name1" type="xs:string"/>
			<xs:element name="Name2" type="xs:string"/>
			<xs:element name="Street" type="xs:string"/>
			<xs:element name="City" type="xs:string"/>
			<xs:element name="State" type="xs:string"/>
			<xs:element name="PostalCode" type="xs:string"/>
			<xs:element name="Country" type="xs:string"/>
			<xs:element name="CountryCode" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Contact">
		<xs:sequence>
			<xs:element name="FirstName" type="xs:string"/>
			<xs:element name="LastName" type="xs:string"/>
			<xs:element name="Title" type="xs:string"/>
			<xs:element name="JobTItle" type="xs:string"/>
			<xs:element name="Phone" type="xs:string"/>
			<xs:element name="Fax" type="xs:string"/>
			<xs:element name="Email" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Discount">
		<xs:sequence>
			<xs:element name="Percentage" type="xs:positiveInteger"/>
			<xs:element name="DaysDue" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Price">
		<xs:sequence>
			<xs:element name="UnitPrice" type="xs:float"/>
			<xs:element name="PricePerUnitOfMeasure" type="xs:float"/>
			<xs:element name="PriceQuotient" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Quantity">
		<xs:sequence>
			<xs:element name="QuantityAmount" type="xs:float"/>
			<xs:element name="PackCode" type="xs:string"/>
			<xs:element name="PackSize" type="xs:int"/>
			<xs:element name="UnitOfMeasure" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Amount">
		<xs:sequence>
			<xs:element name="VAT_Rate" type="xs:float"/>
			<xs:element name="VAT_Amount" type="xs:float"/>
			<xs:element name="Amount_ExclVAT" type="xs:float"/>
			<xs:element name="Amount_InclVAT" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Partner">
		<xs:sequence>
			<xs:element name="SupplierReferenceNo" type="xs:string"/>
			<xs:element name="BuyerReferenceNo" type="xs:string"/>
			<xs:element name="VAT_RegistrationNo" type="xs:string"/>
			<xs:element name="Address" type="ns:Address"/>
			<xs:element name="Contact" type="ns:Contact"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Product">
		<xs:sequence>
			<xs:element name="SupplierPartID" type="xs:string"/>
			<xs:element name="SupplierPartDesc" type="xs:string"/>
			<xs:element name="BuyerPartID" type="xs:string"/>
			<xs:element name="BuyerPartDesc" type="xs:string"/>
			<xs:element name="EAN" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum/Apertum_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Order xmlns:ns="Apertum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Apertum Apertum.xsd ">
  <ns:POHead>
    <ns:OrderDetails>
      <ns:SupplierOrderReference>D92387</ns:SupplierOrderReference>
      <ns:BuyerOrderReference>CO23049</ns:BuyerOrderReference>
      <ns:TextHeader>Purchase Order No PO1300000292</ns:TextHeader>
      <ns:TextFooter>Enjoy</ns:TextFooter>
      <ns:SupplierOrderDate>2013-11-11</ns:SupplierOrderDate>
      <ns:BuyerOrderDate>2013-11-11</ns:BuyerOrderDate>
    </ns:OrderDetails>
    <ns:Currency>
      <ns:CurrencyCode>EUR</ns:CurrencyCode>
    </ns:Currency>
    <ns:TermsOfPayment>
      <ns:Description>Net 45</ns:Description>
      <ns:NetDays>45</ns:NetDays>
      <ns:Discount1>
        <ns:Percentage>10</ns:Percentage>
        <ns:DaysDue>2013-11-02</ns:DaysDue>
      </ns:Discount1>
      <ns:Discount2>
        <ns:Percentage>5</ns:Percentage>
        <ns:DaysDue>2013-12-01</ns:DaysDue>
      </ns:Discount2>
    </ns:TermsOfPayment>
    <ns:TermsOfDelivery>
      <ns:DelivType>Express Shipping with guaranteed delivery date</ns:DelivType>
      <ns:TransportType>sea</ns:TransportType>
    </ns:TermsOfDelivery>
  </ns:POHead>
  <ns:Buyer>
    <ns:SupplierReferenceNo>D92387</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO23049</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 123444</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Daniela Levi</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Marganit 7</ns:Street>
      <ns:City>Nesher</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>98833</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Daniela</ns:FirstName>
      <ns:LastName>Levi</ns:LastName>
      <ns:Title>MR</ns:Title>
      <ns:JobTItle>Nurse</ns:JobTItle>
      <ns:Phone>04-293801</ns:Phone>
      <ns:Fax>04-653092</ns:Fax>
      <ns:Email>daniell@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Buyer>
  <ns:Supplier>
    <ns:SupplierReferenceNo>D92387</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO23049</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 123444</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Rehitey Dororn</ns:Name1>
	  <ns:Name2>Rehitey Dororn</ns:Name2>
      <ns:Street>Hasdna</ns:Street>
      <ns:City>Tira</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>23776</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Ori</ns:FirstName>
      <ns:LastName>Abutbul</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>seller</ns:JobTItle>
      <ns:Phone>04-8293984</ns:Phone>
      <ns:Fax>04-8293984</ns:Fax>
      <ns:Email>oria@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Supplier>
  <ns:DeliverTo>
    <ns:SupplierReferenceNo>D92387</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO23049</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 123444</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Daniela Levi</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Marganit 7</ns:Street>
      <ns:City>Nesher</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>98833</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Daniela</ns:FirstName>
      <ns:LastName>Levi</ns:LastName>
      <ns:Title>Ms</ns:Title>
      <ns:JobTItle>singer</ns:JobTItle>
      <ns:Phone>04-912381</ns:Phone>
      <ns:Fax>08-912381</ns:Fax>
      <ns:Email>daniell@mail.com</ns:Email>
    </ns:Contact>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:SupplierReferenceNo>D92387</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO23049</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 123444</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Hava Albershtain</ns:Name1>
	  <ns:Name2>Hava Albershtain</ns:Name2>
      <ns:Street>frishman</ns:Street>
      <ns:City>Herzeliya</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>56982</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Hava</ns:FirstName>
      <ns:LastName>Albershtain</ns:LastName>
      <ns:Title>Ms</ns:Title>
      <ns:JobTItle>singer</ns:JobTItle>
      <ns:Phone>050292871</ns:Phone>
      <ns:Fax>03-827364</ns:Fax>
      <ns:Email>havaa@gmail.com</ns:Email>
    </ns:Contact>
  </ns:InvoiceTo>
  <ns:POLine>
    <ns:LineNo>1</ns:LineNo>
    <ns:Product>
      <ns:SupplierPartID>pk27278</ns:SupplierPartID>
      <ns:SupplierPartDesc>table</ns:SupplierPartDesc>
      <ns:BuyerPartID>t7209</ns:BuyerPartID>
      <ns:BuyerPartDesc>table</ns:BuyerPartDesc>
      <ns:EAN>mk287392</ns:EAN>
    </ns:Product>
    <ns:Price>
      <ns:UnitPrice>12000</ns:UnitPrice>
      <ns:PricePerUnitOfMeasure>12000</ns:PricePerUnitOfMeasure>
      <ns:PriceQuotient>12000</ns:PriceQuotient>
    </ns:Price>
    <ns:Quantity>
      <ns:QuantityAmount>1</ns:QuantityAmount>
      <ns:PackCode>ygt5523</ns:PackCode>
      <ns:PackSize>9</ns:PackSize>
      <ns:UnitOfMeasure>kg</ns:UnitOfMeasure>
    </ns:Quantity>
    <ns:RequestedDeliveryDate>
      <ns:DateYear>2013</ns:DateYear>
      <ns:DateWeek>42</ns:DateWeek>
      <ns:Date>2013-11-20</ns:Date>
    </ns:RequestedDeliveryDate>
    <ns:Discount>
      <ns:Percentage>15</ns:Percentage>
      <ns:DaysDue>2013-11-20</ns:DaysDue>
    </ns:Discount>
    <ns:Amount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>2040</ns:VAT_Amount>
      <ns:Amount_ExclVAT>2040</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>2040</ns:Amount_InclVAT>
    </ns:Amount>
  </ns:POLine>
  <ns:OrderTotal>
    <ns:NumberOfLines>1</ns:NumberOfLines>
    <ns:TotalAmount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>2040</ns:VAT_Amount>
      <ns:Amount_ExclVAT>2040</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>2040</ns:Amount_InclVAT>
      <ns:VAT_AmountTotal>2040</ns:VAT_AmountTotal>
    </ns:TotalAmount>
  </ns:OrderTotal>
</ns:Order>

=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum/Apertum_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Order xmlns:ns="Apertum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Apertum Apertum.xsd ">
  <ns:POHead>
    <ns:OrderDetails>
      <ns:SupplierOrderReference>IK2837</ns:SupplierOrderReference>
      <ns:BuyerOrderReference>CO382648</ns:BuyerOrderReference>
      <ns:TextHeader>Purchase Order No PO4750686</ns:TextHeader>
      <ns:TextFooter>Enjoy</ns:TextFooter>
      <ns:SupplierOrderDate>2012-12-13</ns:SupplierOrderDate>
      <ns:BuyerOrderDate>2012-12-13</ns:BuyerOrderDate>
    </ns:OrderDetails>
    <ns:Currency>
      <ns:CurrencyCode>USD</ns:CurrencyCode>
    </ns:Currency>
    <ns:TermsOfPayment>
      <ns:Description>Net 30</ns:Description>
      <ns:NetDays>30</ns:NetDays>
      <ns:Discount1>
        <ns:Percentage>5</ns:Percentage>
        <ns:DaysDue>2001-04-20</ns:DaysDue>
      </ns:Discount1>
      <ns:Discount2>
        <ns:Percentage>1</ns:Percentage>
        <ns:DaysDue>2001-01-01</ns:DaysDue>
      </ns:Discount2>
    </ns:TermsOfPayment>
    <ns:TermsOfDelivery>
      <ns:DelivType>Express Shipping with guaranteed delivery date</ns:DelivType>
      <ns:TransportType>air</ns:TransportType>
    </ns:TermsOfDelivery>
  </ns:POHead>
  <ns:Buyer>
    <ns:SupplierReferenceNo>IK2837</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO382648</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 23423</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Eyal Shani</ns:Name1>
      <ns:Name2>Ido Cohen</ns:Name2>
      <ns:Street>Zahal</ns:Street>
      <ns:City>Herzeliya</ns:City>
      <ns:State>N/A</ns:State>
      <ns:PostalCode>56982</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Eyal</ns:FirstName>
      <ns:LastName>Shani</ns:LastName>
      <ns:Title>Bsc</ns:Title>
      <ns:JobTItle>Engineer</ns:JobTItle>
      <ns:Phone>03-863216</ns:Phone>
      <ns:Fax>03-653092</ns:Fax>
      <ns:Email>EyalS@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Buyer>
  <ns:Supplier>
    <ns:SupplierReferenceNo>IK2837</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO382648</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 23423</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>IKEA</ns:Name1>
	  <ns:Name2>IKEA</ns:Name2>
      <ns:Street>Giborey Israel</ns:Street>
      <ns:City>Netanya</ns:City>
      <ns:State>N/A</ns:State>
      <ns:PostalCode>60098</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Avi</ns:FirstName>
      <ns:LastName>Cohen</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>teacher</ns:JobTItle>
      <ns:Phone>04-895623</ns:Phone>
      <ns:Fax>04-784512</ns:Fax>
      <ns:Email>avu@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Supplier>
  <ns:DeliverTo>
    <ns:SupplierReferenceNo>IK2837</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO382648</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 23423</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Eyal Shani</ns:Name1>
	  <ns:Name2>Ido Cohen</ns:Name2>
      <ns:Street>Zahal</ns:Street>
      <ns:City>Herzeliya</ns:City>
      <ns:State>N/A</ns:State>
      <ns:PostalCode>56982</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Eyal</ns:FirstName>
      <ns:LastName>Shani</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>cook</ns:JobTItle>
      <ns:Phone>04-895623</ns:Phone>
      <ns:Fax>08-987654</ns:Fax>
      <ns:Email>eyal@mail.com</ns:Email>
    </ns:Contact>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:SupplierReferenceNo>IK2837</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO382648</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 23423</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Mor Shani</ns:Name1>
	  <ns:Name2>Mor Shani</ns:Name2>
      <ns:Street>Zahal</ns:Street>
      <ns:City>Herzeliya</ns:City>
      <ns:State>N/A</ns:State>
      <ns:PostalCode>56982</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Mor</ns:FirstName>
      <ns:LastName>Shani</ns:LastName>
      <ns:Title>PHD</ns:Title>
      <ns:JobTItle>nurse</ns:JobTItle>
      <ns:Phone>054321896</ns:Phone>
      <ns:Fax>03-653092</ns:Fax>
      <ns:Email>mors@gmail.com</ns:Email>
    </ns:Contact>
  </ns:InvoiceTo>
  <ns:POLine>
    <ns:LineNo>1</ns:LineNo>
    <ns:Product>
      <ns:SupplierPartID>de75356</ns:SupplierPartID>
      <ns:SupplierPartDesc>saucepan black</ns:SupplierPartDesc>
      <ns:BuyerPartID>v533</ns:BuyerPartID>
      <ns:BuyerPartDesc>saucepan black</ns:BuyerPartDesc>
      <ns:EAN>vg664feef</ns:EAN>
    </ns:Product>
    <ns:Price>
      <ns:UnitPrice>100</ns:UnitPrice>
      <ns:PricePerUnitOfMeasure>50.76</ns:PricePerUnitOfMeasure>
      <ns:PriceQuotient>376.9</ns:PriceQuotient>
    </ns:Price>
    <ns:Quantity>
      <ns:QuantityAmount>5</ns:QuantityAmount>
      <ns:PackCode>ygt5554</ns:PackCode>
      <ns:PackSize>60</ns:PackSize>
      <ns:UnitOfMeasure>kg</ns:UnitOfMeasure>
    </ns:Quantity>
    <ns:RequestedDeliveryDate>
      <ns:DateYear>2013</ns:DateYear>
      <ns:DateWeek>45</ns:DateWeek>
      <ns:Date>2012-12-20</ns:Date>
    </ns:RequestedDeliveryDate>
    <ns:Discount>
      <ns:Percentage>5</ns:Percentage>
      <ns:DaysDue>2012-12-20</ns:DaysDue>
    </ns:Discount>
    <ns:Amount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>8.6</ns:VAT_Amount>
      <ns:Amount_ExclVAT>50.76</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>59.36</ns:Amount_InclVAT>
    </ns:Amount>
  </ns:POLine>
  <ns:OrderTotal>
    <ns:NumberOfLines>1</ns:NumberOfLines>
    <ns:TotalAmount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>8.6</ns:VAT_Amount>
      <ns:Amount_ExclVAT>50.76</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>59.36</ns:Amount_InclVAT>
      <ns:VAT_AmountTotal>9</ns:VAT_AmountTotal>
    </ns:TotalAmount>
  </ns:OrderTotal>
</ns:Order>

=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum/Apertum_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Order xmlns:ns="Apertum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Apertum Apertum.xsd ">
  <ns:POHead>
    <ns:OrderDetails>
      <ns:SupplierOrderReference>FT2093</ns:SupplierOrderReference>
      <ns:BuyerOrderReference>CO102983</ns:BuyerOrderReference>
      <ns:TextHeader>Purchase Order No PO400097</ns:TextHeader>
      <ns:TextFooter>Enjoy</ns:TextFooter>
      <ns:SupplierOrderDate>2013-12-13</ns:SupplierOrderDate>
      <ns:BuyerOrderDate>2013-12-13</ns:BuyerOrderDate>
    </ns:OrderDetails>
    <ns:Currency>
      <ns:CurrencyCode>DZD</ns:CurrencyCode>
    </ns:Currency>
    <ns:TermsOfPayment>
      <ns:Description>Net 30</ns:Description>
      <ns:NetDays>30</ns:NetDays>
      <ns:Discount1>
        <ns:Percentage>5</ns:Percentage>
        <ns:DaysDue>2013-11-24</ns:DaysDue>
      </ns:Discount1>
      <ns:Discount2>
        <ns:Percentage>1</ns:Percentage>
        <ns:DaysDue>2014-11-24</ns:DaysDue>
      </ns:Discount2>
    </ns:TermsOfPayment>
    <ns:TermsOfDelivery>
      <ns:DelivType>standarat Shipping</ns:DelivType>
      <ns:TransportType>air</ns:TransportType>
    </ns:TermsOfDelivery>
  </ns:POHead>
  <ns:Buyer>
    <ns:SupplierReferenceNo>FT2093</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO102983</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 29038</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Shikma Shoshana</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Hasadna</ns:Street>
      <ns:City>Tirat Carmel</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>78788</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Shikam</ns:FirstName>
      <ns:LastName>Shoshana</ns:LastName>
      <ns:Title>Bsc</ns:Title>
      <ns:JobTItle>Engineer</ns:JobTItle>
      <ns:Phone>04-098745</ns:Phone>
      <ns:Fax>04-890788</ns:Fax>
      <ns:Email>shikmas@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Buyer>
  <ns:Supplier>
    <ns:SupplierReferenceNo>FT2093</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO102983</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 29038</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Fitness</ns:Name1>
	  <ns:Name2>Fitness</ns:Name2>
      <ns:Street>Mezada</ns:Street>
      <ns:City>Nahariya</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>67444</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Avi</ns:FirstName>
      <ns:LastName>Levi</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>seller</ns:JobTItle>
      <ns:Phone>04-899878</ns:Phone>
      <ns:Fax>04-789989</ns:Fax>
      <ns:Email>avil@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Supplier>
  <ns:DeliverTo>
    <ns:SupplierReferenceNo>FT2093</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO102983</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 29038</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Shikma Shoshana</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Hasadna</ns:Street>
      <ns:City>Tirat Carmel</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>78878</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Shikma</ns:FirstName>
      <ns:LastName>Shoshana</ns:LastName>
      <ns:Title>BSc</ns:Title>
      <ns:JobTItle>Engeneer</ns:JobTItle>
      <ns:Phone>04-098745</ns:Phone>
      <ns:Fax>04-098745</ns:Fax>
      <ns:Email>shikmas@gmail.com</ns:Email>
    </ns:Contact>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:SupplierReferenceNo>FT2093</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO102983</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 29038</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Shikma Shoshana</ns:Name1>
	  <ns:Name2>Shikma Shoshana</ns:Name2>
      <ns:Street>Hasadna</ns:Street>
      <ns:City>Tirat Carmel</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>787878</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Shikma</ns:FirstName>
      <ns:LastName>Shoshana</ns:LastName>
      <ns:Title>BSc</ns:Title>
      <ns:JobTItle>Engineer</ns:JobTItle>
      <ns:Phone>04837265</ns:Phone>
      <ns:Fax>04638923</ns:Fax>
      <ns:Email>shikmas@gmail.com</ns:Email>
    </ns:Contact>
  </ns:InvoiceTo>
  <ns:POLine>
    <ns:LineNo>1</ns:LineNo>
    <ns:Product>
      <ns:SupplierPartID>gy382729</ns:SupplierPartID>
      <ns:SupplierPartDesc>bars</ns:SupplierPartDesc>
      <ns:BuyerPartID>h473</ns:BuyerPartID>
      <ns:BuyerPartDesc>bars</ns:BuyerPartDesc>
      <ns:EAN>dj7783kk</ns:EAN>
    </ns:Product>
    <ns:Price>
      <ns:UnitPrice>4</ns:UnitPrice>
      <ns:PricePerUnitOfMeasure>2</ns:PricePerUnitOfMeasure>
      <ns:PriceQuotient>37</ns:PriceQuotient>
    </ns:Price>
    <ns:Quantity>
      <ns:QuantityAmount>5</ns:QuantityAmount>
      <ns:PackCode>hhy7765</ns:PackCode>
      <ns:PackSize>45</ns:PackSize>
      <ns:UnitOfMeasure>l</ns:UnitOfMeasure>
    </ns:Quantity>
    <ns:RequestedDeliveryDate>
      <ns:DateYear>2013</ns:DateYear>
      <ns:DateWeek>23</ns:DateWeek>
      <ns:Date>2013-04-20</ns:Date>
    </ns:RequestedDeliveryDate>
    <ns:Discount>
      <ns:Percentage>5</ns:Percentage>
      <ns:DaysDue>2013-12-20</ns:DaysDue>
    </ns:Discount>
    <ns:Amount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>8.6</ns:VAT_Amount>
      <ns:Amount_ExclVAT>50.76</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>59.36</ns:Amount_InclVAT>
    </ns:Amount>
  </ns:POLine>
  <ns:OrderTotal>
    <ns:NumberOfLines>1</ns:NumberOfLines>
    <ns:TotalAmount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>8.6</ns:VAT_Amount>
      <ns:Amount_ExclVAT>50.76</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>59.36</ns:Amount_InclVAT>
      <ns:VAT_AmountTotal>9</ns:VAT_AmountTotal>
    </ns:TotalAmount>
  </ns:OrderTotal>
</ns:Order>
