=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by NTT (norg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns="Apertum" targetNamespace="Apertum" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Order">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="POHead">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="OrderDetails">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="SupplierOrderReference" type="xs:string"/>
										<xs:element name="BuyerOrderReference" type="xs:string"/>
										<xs:element name="TextHeader" type="xs:string"/>
										<xs:element name="TextFooter" type="xs:string"/>
										<xs:element name="SupplierOrderDate" type="xs:date"/>
										<xs:element name="BuyerOrderDate" type="xs:date"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Currency">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="CurrencyCode" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="TermsOfPayment">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Description" type="xs:string"/>
										<xs:element name="NetDays" type="xs:int"/>
										<xs:element name="Discount1" type="ns:Discount"/>
										<xs:element name="Discount2" type="ns:Discount"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="TermsOfDelivery">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DelivType" type="xs:string"/>
										<xs:element name="TransportType" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Buyer" type="ns:Partner"/>
				<xs:element name="Supplier" type="ns:Partner"/>
				<xs:element name="DeliverTo" type="ns:Partner"/>
				<xs:element name="InvoiceTo" type="ns:Partner"/>
				<xs:element name="POLine">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LineNo" type="xs:string"/>
							<xs:element name="Product" type="ns:Product"/>
							<xs:element name="Price" type="ns:Price"/>
							<xs:element name="Quantity" type="ns:Quantity"/>
							<xs:element name="RequestedDeliveryDate">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DateYear" type="xs:int"/>
										<xs:element name="DateWeek" type="xs:int"/>
										<xs:element name="Date" type="xs:date"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Discount" type="ns:Discount"/>
							<xs:element name="Amount" type="ns:Amount"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="OrderTotal">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="NumberOfLines" type="xs:positiveInteger"/>
							<xs:element name="TotalAmount">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="ns:Amount">
											<xs:sequence>
												<xs:element name="VAT_AmountTotal" type="xs:int"/>
											</xs:sequence>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Address">
		<xs:sequence>
			<xs:element name="Name1" type="xs:string"/>
			<xs:element name="Name2" type="xs:string"/>
			<xs:element name="Street" type="xs:string"/>
			<xs:element name="City" type="xs:string"/>
			<xs:element name="State" type="xs:string"/>
			<xs:element name="PostalCode" type="xs:string"/>
			<xs:element name="Country" type="xs:string"/>
			<xs:element name="CountryCode" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Contact">
		<xs:sequence>
			<xs:element name="FirstName" type="xs:string"/>
			<xs:element name="LastName" type="xs:string"/>
			<xs:element name="Title" type="xs:string"/>
			<xs:element name="JobTItle" type="xs:string"/>
			<xs:element name="Phone" type="xs:string"/>
			<xs:element name="Fax" type="xs:string"/>
			<xs:element name="Email" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Discount">
		<xs:sequence>
			<xs:element name="Percentage" type="xs:positiveInteger"/>
			<xs:element name="DaysDue" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Price">
		<xs:sequence>
			<xs:element name="UnitPrice" type="xs:float"/>
			<xs:element name="PricePerUnitOfMeasure" type="xs:float"/>
			<xs:element name="PriceQuotient" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Quantity">
		<xs:sequence>
			<xs:element name="QuantityAmount" type="xs:float"/>
			<xs:element name="PackCode" type="xs:string"/>
			<xs:element name="PackSize" type="xs:int"/>
			<xs:element name="UnitOfMeasure" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Amount">
		<xs:sequence>
			<xs:element name="VAT_Rate" type="xs:float"/>
			<xs:element name="VAT_Amount" type="xs:float"/>
			<xs:element name="Amount_ExclVAT" type="xs:float"/>
			<xs:element name="Amount_InclVAT" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Partner">
		<xs:sequence>
			<xs:element name="SupplierReferenceNo" type="xs:string"/>
			<xs:element name="BuyerReferenceNo" type="xs:string"/>
			<xs:element name="VAT_RegistrationNo" type="xs:string"/>
			<xs:element name="Address" type="ns:Address"/>
			<xs:element name="Contact" type="ns:Contact"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Product">
		<xs:sequence>
			<xs:element name="SupplierPartID" type="xs:string"/>
			<xs:element name="SupplierPartDesc" type="xs:string"/>
			<xs:element name="BuyerPartID" type="xs:string"/>
			<xs:element name="BuyerPartDesc" type="xs:string"/>
			<xs:element name="EAN" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum/Apertum_8.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Order xmlns:ns="Apertum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Apertum Apertum.xsd ">
  <ns:POHead>
    <ns:OrderDetails>
      <ns:SupplierOrderReference>ALTR4589</ns:SupplierOrderReference>
      <ns:BuyerOrderReference>CU4895</ns:BuyerOrderReference>
      <ns:TextHeader>Purchase Order No PO100896</ns:TextHeader>
      <ns:TextFooter>Enjoy</ns:TextFooter>
      <ns:SupplierOrderDate>2013-10-16</ns:SupplierOrderDate>
      <ns:BuyerOrderDate>2012-10-16</ns:BuyerOrderDate>
    </ns:OrderDetails>
    <ns:Currency>
      <ns:CurrencyCode>NIS</ns:CurrencyCode>
    </ns:Currency>
    <ns:TermsOfPayment>
      <ns:Description></ns:Description>
      <ns:NetDays>9</ns:NetDays>
      <ns:Discount1>
        <ns:Percentage>78</ns:Percentage>
        <ns:DaysDue>2050-04-20</ns:DaysDue>
      </ns:Discount1>
      <ns:Discount2>
        <ns:Percentage>56</ns:Percentage>
        <ns:DaysDue>2050-01-01</ns:DaysDue>
      </ns:Discount2>
    </ns:TermsOfPayment>
    <ns:TermsOfDelivery>
      <ns:DelivType></ns:DelivType>
      <ns:TransportType></ns:TransportType>
    </ns:TermsOfDelivery>
  </ns:POHead>
  <ns:Buyer>
    <ns:SupplierReferenceNo>ALTR4589</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU4895</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 89654</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1> Dr. Micha Bulis</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Geula 7</ns:Street>
      <ns:City>Ramat Yshay</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>56987</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Micha</ns:FirstName>
      <ns:LastName>Bulis</ns:LastName>
      <ns:Title></ns:Title>
      <ns:JobTItle>Manager</ns:JobTItle>
      <ns:Phone>04-863216</ns:Phone>
      <ns:Fax>04-653092</ns:Fax>
      <ns:Email>michab@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Buyer>
  <ns:Supplier>
    <ns:SupplierReferenceNo>ALTR4589</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU4895</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 89654</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>veribo</ns:Name1>
	  <ns:Name2>veribo</ns:Name2>
      <ns:Street>Malahey Israel</ns:Street>
      <ns:City>Tel Hanan</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>60098</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Avi</ns:FirstName>
      <ns:LastName>Levi</ns:LastName>
      <ns:Title></ns:Title>
      <ns:JobTItle>seller</ns:JobTItle>
      <ns:Phone>04-895623</ns:Phone>
      <ns:Fax>04-784512</ns:Fax>
      <ns:Email>avl@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Supplier>
  <ns:DeliverTo>
    <ns:SupplierReferenceNo>ALTR4589</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU4895</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 89654</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1> Dr. Micha Bulis</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Geula 7</ns:Street>
      <ns:City>Ramat Yshay</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>56987</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Eyal</ns:FirstName>
      <ns:LastName>Banay</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>cook</ns:JobTItle>
      <ns:Phone>04-895623</ns:Phone>
      <ns:Fax>04-987654</ns:Fax>
      <ns:Email>eyal@mail.com</ns:Email>
    </ns:Contact>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:SupplierReferenceNo>ALTR4589</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU4895</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 89654</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1> Dr. Micha Bulis</ns:Name1>
	  <ns:Name2> Dr. Micha Bulis</ns:Name2>
      <ns:Street>Geula 7</ns:Street>
      <ns:City>Ramat Yshay</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>56987</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Mihal</ns:FirstName>
      <ns:LastName>Bulis</ns:LastName>
      <ns:Title>Ms</ns:Title>
      <ns:JobTItle>Manager</ns:JobTItle>
      <ns:Phone>054321896</ns:Phone>
      <ns:Fax>04-653092</ns:Fax>
      <ns:Email>mihab@gmail.com</ns:Email>
    </ns:Contact>
  </ns:InvoiceTo>
  <ns:POLine>
    <ns:LineNo>1</ns:LineNo>
    <ns:Product>
      <ns:SupplierPartID>12234</ns:SupplierPartID>
      <ns:SupplierPartDesc>yeuz</ns:SupplierPartDesc>
      <ns:BuyerPartID>r647</ns:BuyerPartID>
      <ns:BuyerPartDesc>consulting</ns:BuyerPartDesc>
      <ns:EAN>d45568</ns:EAN>
    </ns:Product>
    <ns:Price>
      <ns:UnitPrice>1</ns:UnitPrice>
      <ns:PricePerUnitOfMeasure>1</ns:PricePerUnitOfMeasure>
      <ns:PriceQuotient>10</ns:PriceQuotient>
    </ns:Price>
    <ns:Quantity>
      <ns:QuantityAmount>5</ns:QuantityAmount>
      <ns:PackCode>we7732</ns:PackCode>
      <ns:PackSize>34</ns:PackSize>
      <ns:UnitOfMeasure>unit</ns:UnitOfMeasure>
    </ns:Quantity>
    <ns:RequestedDeliveryDate>
      <ns:DateYear>2145</ns:DateYear>
      <ns:DateWeek>23</ns:DateWeek>
      <ns:Date>2045-12-20</ns:Date>
    </ns:RequestedDeliveryDate>
    <ns:Discount>
      <ns:Percentage>50</ns:Percentage>
      <ns:DaysDue>2043-12-20</ns:DaysDue>
    </ns:Discount>
    <ns:Amount>
      <ns:VAT_Rate>20</ns:VAT_Rate>
      <ns:VAT_Amount>0.17</ns:VAT_Amount>
      <ns:Amount_ExclVAT>20</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>27.3</ns:Amount_InclVAT>
    </ns:Amount>
  </ns:POLine>
  <ns:OrderTotal>
    <ns:NumberOfLines>1</ns:NumberOfLines>
    <ns:TotalAmount>
      <ns:VAT_Rate>20</ns:VAT_Rate>
      <ns:VAT_Amount>0.17</ns:VAT_Amount>
      <ns:Amount_ExclVAT>20</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>27.3</ns:Amount_InclVAT>
      <ns:VAT_AmountTotal>743</ns:VAT_AmountTotal>
    </ns:TotalAmount>
  </ns:OrderTotal>
</ns:Order>

=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum/Apertum_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Order xmlns:ns="Apertum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Apertum Apertum.xsd ">
  <ns:POHead>
    <ns:OrderDetails>
      <ns:SupplierOrderReference>SHUF3213</ns:SupplierOrderReference>
      <ns:BuyerOrderReference>CU43345</ns:BuyerOrderReference>
      <ns:TextHeader>Purchase Order No PO100098</ns:TextHeader>
      <ns:TextFooter>Enjoy</ns:TextFooter>
      <ns:SupplierOrderDate>2013-10-16</ns:SupplierOrderDate>
      <ns:BuyerOrderDate>2012-10-16</ns:BuyerOrderDate>
    </ns:OrderDetails>
    <ns:Currency>
      <ns:CurrencyCode>NIS</ns:CurrencyCode>
    </ns:Currency>
    <ns:TermsOfPayment>
      <ns:Description></ns:Description>
      <ns:NetDays>5</ns:NetDays>
      <ns:Discount1>
        <ns:Percentage>4</ns:Percentage>
        <ns:DaysDue>2050-04-20</ns:DaysDue>
      </ns:Discount1>
      <ns:Discount2>
        <ns:Percentage>45</ns:Percentage>
        <ns:DaysDue>2050-01-01</ns:DaysDue>
      </ns:Discount2>
    </ns:TermsOfPayment>
    <ns:TermsOfDelivery>
      <ns:DelivType></ns:DelivType>
      <ns:TransportType></ns:TransportType>
    </ns:TermsOfDelivery>
  </ns:POHead>
  <ns:Buyer>
    <ns:SupplierReferenceNo>SHUF3213</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU43345</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 23423</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Mihal Hoze</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Bar</ns:Street>
      <ns:City>Afula</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>23444</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Mihal</ns:FirstName>
      <ns:LastName>Hoze</ns:LastName>
      <ns:Title>Ms</ns:Title>
      <ns:JobTItle>Human Resourses</ns:JobTItle>
      <ns:Phone>04-863216</ns:Phone>
      <ns:Fax>04-653092</ns:Fax>
      <ns:Email>mihal@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Buyer>
  <ns:Supplier>
    <ns:SupplierReferenceNo>SHUF3213</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU43345</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 23423</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Sufersal</ns:Name1>
	  <ns:Name2>Sufersal</ns:Name2>
      <ns:Street>Malahey Israel</ns:Street>
      <ns:City>Tel Hanan</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>60098</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Avi</ns:FirstName>
      <ns:LastName>Cohen</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>seller</ns:JobTItle>
      <ns:Phone>04-895623</ns:Phone>
      <ns:Fax>04-784512</ns:Fax>
      <ns:Email>avu@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Supplier>
  <ns:DeliverTo>
    <ns:SupplierReferenceNo>SHUF3213</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU43345</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 23423</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Mihal Hoze</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Bar</ns:Street>
      <ns:City>Afula</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>23444</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Eyal</ns:FirstName>
      <ns:LastName>Bany</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>cook</ns:JobTItle>
      <ns:Phone>04-895623</ns:Phone>
      <ns:Fax>04-987654</ns:Fax>
      <ns:Email>eyal@mail.com</ns:Email>
    </ns:Contact>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:SupplierReferenceNo>SHUF3213</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU43345</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 23423</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Mihal Hoze</ns:Name1>
	  <ns:Name2>Mihal Hoze</ns:Name2>
      <ns:Street>Bar</ns:Street>
      <ns:City>Afula</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>23444</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Mihal</ns:FirstName>
      <ns:LastName>Hoze</ns:LastName>
      <ns:Title>Ms</ns:Title>
      <ns:JobTItle>Human Resources</ns:JobTItle>
      <ns:Phone>054321896</ns:Phone>
      <ns:Fax>04-653092</ns:Fax>
      <ns:Email>mihal@gmail.com</ns:Email>
    </ns:Contact>
  </ns:InvoiceTo>
  <ns:POLine>
    <ns:LineNo>1</ns:LineNo>
    <ns:Product>
      <ns:SupplierPartID>12234</ns:SupplierPartID>
      <ns:SupplierPartDesc>tomatos</ns:SupplierPartDesc>
      <ns:BuyerPartID>r647</ns:BuyerPartID>
      <ns:BuyerPartDesc>shery tomatos</ns:BuyerPartDesc>
      <ns:EAN>m33345</ns:EAN>
    </ns:Product>
    <ns:Price>
      <ns:UnitPrice>1</ns:UnitPrice>
      <ns:PricePerUnitOfMeasure>1</ns:PricePerUnitOfMeasure>
      <ns:PriceQuotient>10</ns:PriceQuotient>
    </ns:Price>
    <ns:Quantity>
      <ns:QuantityAmount>5</ns:QuantityAmount>
      <ns:PackCode>we7732</ns:PackCode>
      <ns:PackSize>20</ns:PackSize>
      <ns:UnitOfMeasure>kg</ns:UnitOfMeasure>
    </ns:Quantity>
    <ns:RequestedDeliveryDate>
      <ns:DateYear>2013</ns:DateYear>
      <ns:DateWeek>45</ns:DateWeek>
      <ns:Date>2013-12-20</ns:Date>
    </ns:RequestedDeliveryDate>
    <ns:Discount>
      <ns:Percentage>5</ns:Percentage>
      <ns:DaysDue>2014-12-20</ns:DaysDue>
    </ns:Discount>
    <ns:Amount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>0.17</ns:VAT_Amount>
      <ns:Amount_ExclVAT>20</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>27.3</ns:Amount_InclVAT>
    </ns:Amount>
  </ns:POLine>
  <ns:OrderTotal>
    <ns:NumberOfLines>1</ns:NumberOfLines>
    <ns:TotalAmount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>0.17</ns:VAT_Amount>
      <ns:Amount_ExclVAT>20</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>27.3</ns:Amount_InclVAT>
      <ns:VAT_AmountTotal>7</ns:VAT_AmountTotal>
    </ns:TotalAmount>
  </ns:OrderTotal>
</ns:Order>

=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum/Apertum_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Order xmlns:ns="Apertum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Apertum Apertum.xsd ">
  <ns:POHead>
    <ns:OrderDetails>
      <ns:SupplierOrderReference>GR38291</ns:SupplierOrderReference>
      <ns:BuyerOrderReference>CO10929</ns:BuyerOrderReference>
      <ns:TextHeader>Purchase Order No PO475983240</ns:TextHeader>
      <ns:TextFooter>Enjoy</ns:TextFooter>
      <ns:SupplierOrderDate>2014-03-02</ns:SupplierOrderDate>
      <ns:BuyerOrderDate>2012-03-02</ns:BuyerOrderDate>
    </ns:OrderDetails>
    <ns:Currency>
      <ns:CurrencyCode>KPW</ns:CurrencyCode>
    </ns:Currency>
    <ns:TermsOfPayment>
      <ns:Description>Net 45</ns:Description>
      <ns:NetDays>45</ns:NetDays>
      <ns:Discount1>
        <ns:Percentage>15</ns:Percentage>
        <ns:DaysDue>2001-05-24</ns:DaysDue>
      </ns:Discount1>
      <ns:Discount2>
        <ns:Percentage>20</ns:Percentage>
        <ns:DaysDue>2012-05-12</ns:DaysDue>
      </ns:Discount2>
    </ns:TermsOfPayment>
    <ns:TermsOfDelivery>
      <ns:DelivType>Standart Shipping </ns:DelivType>
      <ns:TransportType>sea</ns:TransportType>
    </ns:TermsOfDelivery>
  </ns:POHead>
  <ns:Buyer>
    <ns:SupplierReferenceNo>GR38291</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO10929</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 12346</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Alona Horev</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Khavazelet 33</ns:Street>
      <ns:City>Hod Hashron</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>23493</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Alona</ns:FirstName>
      <ns:LastName>Horev</ns:LastName>
      <ns:Title>Bsc</ns:Title>
      <ns:JobTItle>Engineer</ns:JobTItle>
      <ns:Phone>03-123864</ns:Phone>
      <ns:Fax>03-123864</ns:Fax>
      <ns:Email>alonah@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Buyer>
  <ns:Supplier>
    <ns:SupplierReferenceNo>GR38291</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO10929</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 12346</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Modgal</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Sderot Hanasy</ns:Street>
      <ns:City>Netanya</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>09835</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Ziva</ns:FirstName>
      <ns:LastName>Amir</ns:LastName>
      <ns:Title>Ms</ns:Title>
      <ns:JobTItle>Sales</ns:JobTItle>
      <ns:Phone>09-837463</ns:Phone>
      <ns:Fax>09-837463</ns:Fax>
      <ns:Email>ziva@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Supplier>
  <ns:DeliverTo>
    <ns:SupplierReferenceNo>GR38291</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO10929</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 23423</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Alona Horev</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Khavazelet 33</ns:Street>
      <ns:City>Hod Hashron</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>23493</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Alona</ns:FirstName>
      <ns:LastName>Horev</ns:LastName>
      <ns:Title>Ms</ns:Title>
      <ns:JobTItle>Engineer</ns:JobTItle>
      <ns:Phone>03-123864</ns:Phone>
      <ns:Fax>03-123864</ns:Fax>
      <ns:Email>eyal@mail.com</ns:Email>
    </ns:Contact>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:SupplierReferenceNo>GR38291</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CO10929</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 12346</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Alona Horev</ns:Name1>
	  <ns:Name2>Alona Horev</ns:Name2>
      <ns:Street>Khavazelet</ns:Street>
      <ns:City>Hod Hashron</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>23493</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Alona</ns:FirstName>
      <ns:LastName>Horev</ns:LastName>
      <ns:Title>Bsc</ns:Title>
      <ns:JobTItle>Engineer</ns:JobTItle>
      <ns:Phone>053846372</ns:Phone>
      <ns:Fax>03-6530920</ns:Fax>
      <ns:Email>alonah@gmail.com</ns:Email>
    </ns:Contact>
  </ns:InvoiceTo>
  <ns:POLine>
    <ns:LineNo>1</ns:LineNo>
    <ns:Product>
      <ns:SupplierPartID>293489</ns:SupplierPartID>
      <ns:SupplierPartDesc>iron</ns:SupplierPartDesc>
      <ns:BuyerPartID>d203</ns:BuyerPartID>
      <ns:BuyerPartDesc>iron</ns:BuyerPartDesc>
      <ns:EAN>alskd83749</ns:EAN>
    </ns:Product>
    <ns:Price>
      <ns:UnitPrice>23</ns:UnitPrice>
      <ns:PricePerUnitOfMeasure>2.3</ns:PricePerUnitOfMeasure>
      <ns:PriceQuotient>2.3</ns:PriceQuotient>
    </ns:Price>
    <ns:Quantity>
      <ns:QuantityAmount>20</ns:QuantityAmount>
      <ns:PackCode>8474he</ns:PackCode>
      <ns:PackSize>200</ns:PackSize>
      <ns:UnitOfMeasure>kg</ns:UnitOfMeasure>
    </ns:Quantity>
    <ns:RequestedDeliveryDate>
      <ns:DateYear>2013</ns:DateYear>
      <ns:DateWeek>23</ns:DateWeek>
      <ns:Date>2012-06-12</ns:Date>
    </ns:RequestedDeliveryDate>
    <ns:Discount>
      <ns:Percentage>15</ns:Percentage>
      <ns:DaysDue>2014-12-20</ns:DaysDue>
    </ns:Discount>
    <ns:Amount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>23</ns:VAT_Amount>
      <ns:Amount_ExclVAT>20.3</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>20.3</ns:Amount_InclVAT>
    </ns:Amount>
  </ns:POLine>
  <ns:OrderTotal>
    <ns:NumberOfLines>1</ns:NumberOfLines>
    <ns:TotalAmount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>23</ns:VAT_Amount>
      <ns:Amount_ExclVAT>20.3</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>20.3</ns:Amount_InclVAT>
      <ns:VAT_AmountTotal>12</ns:VAT_AmountTotal>
    </ns:TotalAmount>
  </ns:OrderTotal>
</ns:Order>
