=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by NTT (norg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns="Apertum" targetNamespace="Apertum" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Order">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="POHead">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="OrderDetails">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="SupplierOrderReference" type="xs:string"/>
										<xs:element name="BuyerOrderReference" type="xs:string"/>
										<xs:element name="TextHeader" type="xs:string"/>
										<xs:element name="TextFooter" type="xs:string"/>
										<xs:element name="SupplierOrderDate" type="xs:date"/>
										<xs:element name="BuyerOrderDate" type="xs:date"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Currency">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="CurrencyCode" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="TermsOfPayment">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Description" type="xs:string"/>
										<xs:element name="NetDays" type="xs:int"/>
										<xs:element name="Discount1" type="ns:Discount"/>
										<xs:element name="Discount2" type="ns:Discount"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="TermsOfDelivery">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DelivType" type="xs:string"/>
										<xs:element name="TransportType" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Buyer" type="ns:Partner"/>
				<xs:element name="Supplier" type="ns:Partner"/>
				<xs:element name="DeliverTo" type="ns:Partner"/>
				<xs:element name="InvoiceTo" type="ns:Partner"/>
				<xs:element name="POLine">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LineNo" type="xs:string"/>
							<xs:element name="Product" type="ns:Product"/>
							<xs:element name="Price" type="ns:Price"/>
							<xs:element name="Quantity" type="ns:Quantity"/>
							<xs:element name="RequestedDeliveryDate">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DateYear" type="xs:int"/>
										<xs:element name="DateWeek" type="xs:int"/>
										<xs:element name="Date" type="xs:date"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Discount" type="ns:Discount"/>
							<xs:element name="Amount" type="ns:Amount"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="OrderTotal">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="NumberOfLines" type="xs:positiveInteger"/>
							<xs:element name="TotalAmount">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="ns:Amount">
											<xs:sequence>
												<xs:element name="VAT_AmountTotal" type="xs:int"/>
											</xs:sequence>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Address">
		<xs:sequence>
			<xs:element name="Name1" type="xs:string"/>
			<xs:element name="Name2" type="xs:string"/>
			<xs:element name="Street" type="xs:string"/>
			<xs:element name="City" type="xs:string"/>
			<xs:element name="State" type="xs:string"/>
			<xs:element name="PostalCode" type="xs:string"/>
			<xs:element name="Country" type="xs:string"/>
			<xs:element name="CountryCode" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Contact">
		<xs:sequence>
			<xs:element name="FirstName" type="xs:string"/>
			<xs:element name="LastName" type="xs:string"/>
			<xs:element name="Title" type="xs:string"/>
			<xs:element name="JobTItle" type="xs:string"/>
			<xs:element name="Phone" type="xs:string"/>
			<xs:element name="Fax" type="xs:string"/>
			<xs:element name="Email" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Discount">
		<xs:sequence>
			<xs:element name="Percentage" type="xs:positiveInteger"/>
			<xs:element name="DaysDue" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Price">
		<xs:sequence>
			<xs:element name="UnitPrice" type="xs:float"/>
			<xs:element name="PricePerUnitOfMeasure" type="xs:float"/>
			<xs:element name="PriceQuotient" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Quantity">
		<xs:sequence>
			<xs:element name="QuantityAmount" type="xs:float"/>
			<xs:element name="PackCode" type="xs:string"/>
			<xs:element name="PackSize" type="xs:int"/>
			<xs:element name="UnitOfMeasure" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Amount">
		<xs:sequence>
			<xs:element name="VAT_Rate" type="xs:float"/>
			<xs:element name="VAT_Amount" type="xs:float"/>
			<xs:element name="Amount_ExclVAT" type="xs:float"/>
			<xs:element name="Amount_InclVAT" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Partner">
		<xs:sequence>
			<xs:element name="SupplierReferenceNo" type="xs:string"/>
			<xs:element name="BuyerReferenceNo" type="xs:string"/>
			<xs:element name="VAT_RegistrationNo" type="xs:string"/>
			<xs:element name="Address" type="ns:Address"/>
			<xs:element name="Contact" type="ns:Contact"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Product">
		<xs:sequence>
			<xs:element name="SupplierPartID" type="xs:string"/>
			<xs:element name="SupplierPartDesc" type="xs:string"/>
			<xs:element name="BuyerPartID" type="xs:string"/>
			<xs:element name="BuyerPartDesc" type="xs:string"/>
			<xs:element name="EAN" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum/Apertum_10.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Order xmlns:ns="Apertum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Apertum Apertum.xsd ">
  <ns:POHead>
    <ns:OrderDetails>
      <ns:SupplierOrderReference>yesp7896</ns:SupplierOrderReference>
      <ns:BuyerOrderReference>CU42365</ns:BuyerOrderReference>
      <ns:TextHeader>Purchase Order No PO10078932</ns:TextHeader>
      <ns:TextFooter>Enjoy</ns:TextFooter>
      <ns:SupplierOrderDate>2013-10-16</ns:SupplierOrderDate>
      <ns:BuyerOrderDate>2012-10-16</ns:BuyerOrderDate>
    </ns:OrderDetails>
    <ns:Currency>
      <ns:CurrencyCode>NIS</ns:CurrencyCode>
    </ns:Currency>
    <ns:TermsOfPayment>
      <ns:Description></ns:Description>
      <ns:NetDays>55</ns:NetDays>
      <ns:Discount1>
        <ns:Percentage>58</ns:Percentage>
        <ns:DaysDue>2050-04-20</ns:DaysDue>
      </ns:Discount1>
      <ns:Discount2>
        <ns:Percentage>45</ns:Percentage>
        <ns:DaysDue>2050-01-01</ns:DaysDue>
      </ns:Discount2>
    </ns:TermsOfPayment>
    <ns:TermsOfDelivery>
      <ns:DelivType></ns:DelivType>
      <ns:TransportType></ns:TransportType>
    </ns:TermsOfDelivery>
  </ns:POHead>
  <ns:Buyer>
    <ns:SupplierReferenceNo>yesp7896</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU42365</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 52147</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Dr. Yaron Karzag</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>etgar 3</ns:Street>
      <ns:City>Tira</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>23444</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Yaron</ns:FirstName>
      <ns:LastName>Karzag</ns:LastName>
      <ns:Title></ns:Title>
      <ns:JobTItle></ns:JobTItle>
      <ns:Phone>04-863216</ns:Phone>
      <ns:Fax>04-653092</ns:Fax>
      <ns:Email>yaron@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Buyer>
  <ns:Supplier>
    <ns:SupplierReferenceNo>yesp7896</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU42365</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 52147</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>hotmobile</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Malahey Israel</ns:Street>
      <ns:City>Tel Aviv</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>60098</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Meir</ns:FirstName>
      <ns:LastName>Cohen</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>seller</ns:JobTItle>
      <ns:Phone>04-895623</ns:Phone>
      <ns:Fax>04-784512</ns:Fax>
      <ns:Email>mer@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Supplier>
  <ns:DeliverTo>
    <ns:SupplierReferenceNo>yesp7896</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU42365</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 52147</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Dr. Yaron Karzag</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>etgar 3</ns:Street>
      <ns:City>Tira</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>23444</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Yaron</ns:FirstName>
      <ns:LastName>Karzag</ns:LastName>
      <ns:Title></ns:Title>
      <ns:JobTItle></ns:JobTItle>
      <ns:Phone>04-863216</ns:Phone>
      <ns:Fax>04-653092</ns:Fax>
      <ns:Email>yaron@gmail.com</ns:Email>
    </ns:Contact>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:SupplierReferenceNo>yesp7896</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU42365</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 52147</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Dr. Yaron Karzag</ns:Name1>
	  <ns:Name2>Dr. Yaron Karzag</ns:Name2>
      <ns:Street>etgar 3</ns:Street>
      <ns:City>Tira</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>23444</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Yaron</ns:FirstName>
      <ns:LastName>Karzag</ns:LastName>
      <ns:Title></ns:Title>
      <ns:JobTItle></ns:JobTItle>
      <ns:Phone>04-863216</ns:Phone>
      <ns:Fax>04-653092</ns:Fax>
      <ns:Email>yaron@gmail.com</ns:Email>
    </ns:Contact>
  </ns:InvoiceTo>
  <ns:POLine>
    <ns:LineNo>1</ns:LineNo>
    <ns:Product>
      <ns:SupplierPartID>12234</ns:SupplierPartID>
      <ns:SupplierPartDesc>tomatos</ns:SupplierPartDesc>
      <ns:BuyerPartID>r647</ns:BuyerPartID>
      <ns:BuyerPartDesc>shery tomatos</ns:BuyerPartDesc>
      <ns:EAN>m33345</ns:EAN>
    </ns:Product>
    <ns:Price>
      <ns:UnitPrice>1</ns:UnitPrice>
      <ns:PricePerUnitOfMeasure>1</ns:PricePerUnitOfMeasure>
      <ns:PriceQuotient>10</ns:PriceQuotient>
    </ns:Price>
    <ns:Quantity>
      <ns:QuantityAmount>5</ns:QuantityAmount>
      <ns:PackCode>we7732</ns:PackCode>
      <ns:PackSize>20</ns:PackSize>
      <ns:UnitOfMeasure>kg</ns:UnitOfMeasure>
    </ns:Quantity>
    <ns:RequestedDeliveryDate>
      <ns:DateYear>2013</ns:DateYear>
      <ns:DateWeek>45</ns:DateWeek>
      <ns:Date>2013-12-20</ns:Date>
    </ns:RequestedDeliveryDate>
    <ns:Discount>
      <ns:Percentage>5</ns:Percentage>
      <ns:DaysDue>2014-12-20</ns:DaysDue>
    </ns:Discount>
    <ns:Amount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>0.17</ns:VAT_Amount>
      <ns:Amount_ExclVAT>20</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>27.3</ns:Amount_InclVAT>
    </ns:Amount>
  </ns:POLine>
  <ns:OrderTotal>
    <ns:NumberOfLines>1</ns:NumberOfLines>
    <ns:TotalAmount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>0.17</ns:VAT_Amount>
      <ns:Amount_ExclVAT>20</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>27.3</ns:Amount_InclVAT>
      <ns:VAT_AmountTotal>96</ns:VAT_AmountTotal>
    </ns:TotalAmount>
  </ns:OrderTotal>
</ns:Order>

=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum/Apertum_9.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Order xmlns:ns="Apertum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Apertum Apertum.xsd ">
  <ns:POHead>
    <ns:OrderDetails>
      <ns:SupplierOrderReference>hot5689</ns:SupplierOrderReference>
      <ns:BuyerOrderReference>CU4894</ns:BuyerOrderReference>
      <ns:TextHeader>Purchase Order No PO100789</ns:TextHeader>
      <ns:TextFooter>Enjoy</ns:TextFooter>
      <ns:SupplierOrderDate>2013-10-16</ns:SupplierOrderDate>
      <ns:BuyerOrderDate>2012-10-16</ns:BuyerOrderDate>
    </ns:OrderDetails>
    <ns:Currency>
      <ns:CurrencyCode>NIS</ns:CurrencyCode>
    </ns:Currency>
    <ns:TermsOfPayment>
      <ns:Description></ns:Description>
      <ns:NetDays>6</ns:NetDays>
      <ns:Discount1>
        <ns:Percentage>89</ns:Percentage>
        <ns:DaysDue>2050-04-20</ns:DaysDue>
      </ns:Discount1>
      <ns:Discount2>
        <ns:Percentage>78</ns:Percentage>
        <ns:DaysDue>2050-01-01</ns:DaysDue>
      </ns:Discount2>
    </ns:TermsOfPayment>
    <ns:TermsOfDelivery>
      <ns:DelivType></ns:DelivType>
      <ns:TransportType></ns:TransportType>
    </ns:TermsOfDelivery>
  </ns:POHead>
  <ns:Buyer>
    <ns:SupplierReferenceNo>hot5689</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU4894</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 56932</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Mrs. Lilah Perez</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Moshe Dayan</ns:Street>
      <ns:City>Haifa</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>25874</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Mihal</ns:FirstName>
      <ns:LastName>Hoze</ns:LastName>
      <ns:Title>Ms</ns:Title>
      <ns:JobTItle>Human Resourses</ns:JobTItle>
      <ns:Phone>04-863216</ns:Phone>
      <ns:Fax>04-653092</ns:Fax>
      <ns:Email>mihal@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Buyer>
  <ns:Supplier>
    <ns:SupplierReferenceNo>hot5689</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU4894</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 56932</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Sufersal</ns:Name1>
	  <ns:Name2>Sufersal</ns:Name2>
      <ns:Street>Malahey Israel</ns:Street>
      <ns:City>Tel Hanan</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>60098</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Avi</ns:FirstName>
      <ns:LastName>Cohen</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>seller</ns:JobTItle>
      <ns:Phone>04-895623</ns:Phone>
      <ns:Fax>04-784512</ns:Fax>
      <ns:Email>avu@gmail.com</ns:Email>
    </ns:Contact>
  </ns:Supplier>
  <ns:DeliverTo>
    <ns:SupplierReferenceNo>hot5689</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU4894</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 56932</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Mrs. Lilah Perez</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Moshe Dayan</ns:Street>
      <ns:City>Haifa</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>25874</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Lilah</ns:FirstName>
      <ns:LastName>Perez</ns:LastName>
      <ns:Title></ns:Title>
      <ns:JobTItle>Team Manager</ns:JobTItle>
      <ns:Phone>04-895623</ns:Phone>
      <ns:Fax>04-987654</ns:Fax>
      <ns:Email>lilip@mail.com</ns:Email>
    </ns:Contact>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:SupplierReferenceNo>hot5689</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>CU4894</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 56932</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Mrs. Lilah Perez</ns:Name1>
	  <ns:Name2>Mrs. Lilah Perez</ns:Name2>
      <ns:Street>Moshe Dayan</ns:Street>
      <ns:City>Haifa</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>25874</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Lilah</ns:FirstName>
      <ns:LastName>Perez</ns:LastName>
      <ns:Title></ns:Title>
      <ns:JobTItle>Team Manager</ns:JobTItle>
      <ns:Phone>04-895623</ns:Phone>
      <ns:Fax>04-987654</ns:Fax>
      <ns:Email>lilip@mail.com</ns:Email>
    </ns:Contact>
  </ns:InvoiceTo>
  <ns:POLine>
    <ns:LineNo>1</ns:LineNo>
    <ns:Product>
      <ns:SupplierPartID>59873</ns:SupplierPartID>
      <ns:SupplierPartDesc>galaxy</ns:SupplierPartDesc>
      <ns:BuyerPartID>g930</ns:BuyerPartID>
      <ns:BuyerPartDesc>sumsung</ns:BuyerPartDesc>
      <ns:EAN>d65981</ns:EAN>
    </ns:Product>
    <ns:Price>
      <ns:UnitPrice>3000</ns:UnitPrice>
      <ns:PricePerUnitOfMeasure>3000</ns:PricePerUnitOfMeasure>
      <ns:PriceQuotient>10</ns:PriceQuotient>
    </ns:Price>
    <ns:Quantity>
      <ns:QuantityAmount>1</ns:QuantityAmount>
      <ns:PackCode>we7732</ns:PackCode>
      <ns:PackSize>20</ns:PackSize>
      <ns:UnitOfMeasure>mg</ns:UnitOfMeasure>
    </ns:Quantity>
    <ns:RequestedDeliveryDate>
      <ns:DateYear>2013</ns:DateYear>
      <ns:DateWeek>45</ns:DateWeek>
      <ns:Date>2013-12-20</ns:Date>
    </ns:RequestedDeliveryDate>
    <ns:Discount>
      <ns:Percentage>5</ns:Percentage>
      <ns:DaysDue>2014-12-20</ns:DaysDue>
    </ns:Discount>
    <ns:Amount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>0.17</ns:VAT_Amount>
      <ns:Amount_ExclVAT>20</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>27.3</ns:Amount_InclVAT>
    </ns:Amount>
  </ns:POLine>
  <ns:OrderTotal>
    <ns:NumberOfLines>1</ns:NumberOfLines>
    <ns:TotalAmount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>0.17</ns:VAT_Amount>
      <ns:Amount_ExclVAT>20</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>27.3</ns:Amount_InclVAT>
      <ns:VAT_AmountTotal>45</ns:VAT_AmountTotal>
    </ns:TotalAmount>
  </ns:OrderTotal>
</ns:Order>

=== shraga89/ontobuilderDev/ontobuilder.io/src/test/resources/Apertum/Apertum_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:Order xmlns:ns="Apertum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Apertum Apertum.xsd ">
  <ns:POHead>
    <ns:OrderDetails>
      <ns:SupplierOrderReference>Med2938</ns:SupplierOrderReference>
      <ns:BuyerOrderReference>Shap1029</ns:BuyerOrderReference>
      <ns:TextHeader>Purchase Order No PO200003</ns:TextHeader>
      <ns:TextFooter>Enjoy</ns:TextFooter>
      <ns:SupplierOrderDate>2002-12-02</ns:SupplierOrderDate>
      <ns:BuyerOrderDate>2012-12-02</ns:BuyerOrderDate>
    </ns:OrderDetails>
    <ns:Currency>
      <ns:CurrencyCode>EUR</ns:CurrencyCode>
    </ns:Currency>
    <ns:TermsOfPayment>
      <ns:Description>Net</ns:Description>
      <ns:NetDays>0</ns:NetDays>
      <ns:Discount1>
        <ns:Percentage>35</ns:Percentage>
        <ns:DaysDue>2032-01-10</ns:DaysDue>
      </ns:Discount1>
      <ns:Discount2>
        <ns:Percentage>10</ns:Percentage>
        <ns:DaysDue>2045-01-01</ns:DaysDue>
      </ns:Discount2>
    </ns:TermsOfPayment>
    <ns:TermsOfDelivery>
      <ns:DelivType></ns:DelivType>
      <ns:TransportType></ns:TransportType>
    </ns:TermsOfDelivery>
  </ns:POHead>
  <ns:Buyer>
    <ns:SupplierReferenceNo>Med2938</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>Shap1029</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 29091</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Saron BenMoshe</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Habareket</ns:Street>
      <ns:City>Petah Tikva</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>87665</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Gad</ns:FirstName>
      <ns:LastName>Zur</ns:LastName>
      <ns:Title>Bsc</ns:Title>
      <ns:JobTItle>Engineer</ns:JobTItle>
      <ns:Phone>03-293833</ns:Phone>
      <ns:Fax>03-293833</ns:Fax>
      <ns:Email>gadz@medatech.com</ns:Email>
    </ns:Contact>
  </ns:Buyer>
  <ns:Supplier>
    <ns:SupplierReferenceNo>Med2938</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>Shap1029</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 29091</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Medatech</ns:Name1>
	  <ns:Name2>Medatech</ns:Name2>
      <ns:Street>Hasadna 3</ns:Street>
      <ns:City>Tirat Carmel</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>33865</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Meir</ns:FirstName>
      <ns:LastName>Gabay</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>Manager</ns:JobTItle>
      <ns:Phone>072-73645098</ns:Phone>
      <ns:Fax>072-73645098</ns:Fax>
      <ns:Email>meirg@medatech.com</ns:Email>
    </ns:Contact>
  </ns:Supplier>
  <ns:DeliverTo>
    <ns:SupplierReferenceNo>Med2938</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>Shap1029</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 29091</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Shron Ben Moshe</ns:Name1>
	  <ns:Name2></ns:Name2>
      <ns:Street>Habarekt</ns:Street>
      <ns:City>Petah Tikva</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>87665</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Oren</ns:FirstName>
      <ns:LastName>Vaisman</ns:LastName>
      <ns:Title>Mr</ns:Title>
      <ns:JobTItle>TechSupport</ns:JobTItle>
      <ns:Phone>03-948575</ns:Phone>
      <ns:Fax>03-948575</ns:Fax>
      <ns:Email>orenv@mail.com</ns:Email>
    </ns:Contact>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:SupplierReferenceNo>Med2938</ns:SupplierReferenceNo>
    <ns:BuyerReferenceNo>Shap1029</ns:BuyerReferenceNo>
    <ns:VAT_RegistrationNo>IL 29091</ns:VAT_RegistrationNo>
    <ns:Address>
      <ns:Name1>Mor Shani</ns:Name1>
	  <ns:Name2>Mor Shani</ns:Name2>
      <ns:Street>Zahal</ns:Street>
      <ns:City>Herzeliya</ns:City>
      <ns:State></ns:State>
      <ns:PostalCode>56982</ns:PostalCode>
      <ns:Country>Israel</ns:Country>
      <ns:CountryCode>IL</ns:CountryCode>
    </ns:Address>
    <ns:Contact>
      <ns:FirstName>Mor</ns:FirstName>
      <ns:LastName>Shani</ns:LastName>
      <ns:Title>PHD</ns:Title>
      <ns:JobTItle>Manager</ns:JobTItle>
      <ns:Phone>052093843</ns:Phone>
      <ns:Fax>03-653092</ns:Fax>
      <ns:Email>mors@gmail.com</ns:Email>
    </ns:Contact>
  </ns:InvoiceTo>
  <ns:POLine>
    <ns:LineNo>1</ns:LineNo>
    <ns:Product>
      <ns:SupplierPartID>po73463</ns:SupplierPartID>
      <ns:SupplierPartDesc>reports in priority</ns:SupplierPartDesc>
      <ns:BuyerPartID>b276</ns:BuyerPartID>
      <ns:BuyerPartDesc>services medatech</ns:BuyerPartDesc>
      <ns:EAN>ask9303alk</ns:EAN>
    </ns:Product>
    <ns:Price>
      <ns:UnitPrice>200</ns:UnitPrice>
      <ns:PricePerUnitOfMeasure>200</ns:PricePerUnitOfMeasure>
      <ns:PriceQuotient>10000</ns:PriceQuotient>
    </ns:Price>
    <ns:Quantity>
      <ns:QuantityAmount>5</ns:QuantityAmount>
      <ns:PackCode></ns:PackCode>
      <ns:PackSize>45</ns:PackSize>
      <ns:UnitOfMeasure>unit</ns:UnitOfMeasure>
    </ns:Quantity>
    <ns:RequestedDeliveryDate>
      <ns:DateYear>2013</ns:DateYear>
      <ns:DateWeek>50</ns:DateWeek>
      <ns:Date>2013-07-20</ns:Date>
    </ns:RequestedDeliveryDate>
    <ns:Discount>
      <ns:Percentage>5</ns:Percentage>
      <ns:DaysDue>2030-12-20</ns:DaysDue>
    </ns:Discount>
    <ns:Amount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>670</ns:VAT_Amount>
      <ns:Amount_ExclVAT>10000</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>10679</ns:Amount_InclVAT>
    </ns:Amount>
  </ns:POLine>
  <ns:OrderTotal>
    <ns:NumberOfLines>1</ns:NumberOfLines>
    <ns:TotalAmount>
      <ns:VAT_Rate>17</ns:VAT_Rate>
      <ns:VAT_Amount>670</ns:VAT_Amount>
      <ns:Amount_ExclVAT>10000</ns:Amount_ExclVAT>
      <ns:Amount_InclVAT>10679</ns:Amount_InclVAT>
      <ns:VAT_AmountTotal>670</ns:VAT_AmountTotal>
    </ns:TotalAmount>
  </ns:OrderTotal>
</ns:Order>
